### ISSUE TITLE
work-manager addon remains in "Unknown" state since #614

### ISSUE THREAD

**Issue by nirs** [stolostron/multicloud-operators-foundation#616]
Since commit 629b9e066e342d7c0ce8141aa2f1f3ca5128c771, when installing work-manager addon
(using clusteradm) the addon remains in "Unknown" state, and the `klusterlet-addon-workmgr`
deployment is not deployed on the managed clusters.

## How to reproduce

Enable the addon:

```
$ clusteradm addon enable --names work-manager --clusters dr1,dr2 --context hub
```

Watch the addon status - it remains in "Unknown" status:

```
$ kubectl get managedclusteraddon -A --context hub | grep work-manager
dr1         work-manager                  Unknown
dr2         work-manager                  Unknown
```

The same flow works with commit 7c7eb070997853cc355facf783fcf9be6a5c5d77.

I'm not sure that this usage is correct, since we install the stolostron addon
using upstream `clusteradm` on a setup created using clusteradm, but this works
for us since March 2023.

Ideally we would not be using main so we are not affected by such changes, but
we have no recent tag or release.

**Comment by zhiweiyin318** [comment]
@nirs this addon only works on OCP cluster, so need check if the spoke cluster is OCP. 
we also need check if the addon manifestWork is created or not since you said klusterlet-addon-workmgr
deployment is not deployed on the managed clusters.
```
kubectl get manifestwork -n dr1
```
and also need the logs of com-controller pods to debug.

**Comment by nirs** [comment]
@zhiweiyin318 this addon worked for us without ocp for a while. We install it on upstream
OCM in the Ramen testing environment based on minikube clusters. We don't have yet an
upstream release but we hope it that it will be possible to install Ramen and its
dependencies in upstream k8s.

Do we have a way to increase the log verbosify of ocm-controller? I see only this:

```
W0524 16:06:47.212487       1 autodetect_controller.go:132] will reconcile since failed to add labels to ManagedClusterInfo dr1, Operation cannot be fulfilled on managedclusterinfos.internal.open-cluster-management.io "dr1": the object has been modified; please apply your changes to the latest version and try again
W0524 16:06:47.230610       1 autodetect_controller.go:132] will reconcile since failed to add labels to ManagedClusterInfo dr1, Operation cannot be fulfilled on managedclusterinfos.internal.open-cluster-management.io "dr1": the object has been modified; please apply your changes to the latest version and try again
E0524 16:06:47.235228       1 clusterinfo_controller.go:270] failed to get log cert secret open-cluster-management/ocm-klusterlet-self-signed-secrets: Secret "ocm-klusterlet-self-signed-secrets" not found
E0524 16:06:47.235249       1 clusterinfo_controller.go:188] failed to get log CA. Secret "ocm-klusterlet-self-signed-secrets" not found
```

It would be helpful to get debug level logs for all reconciles.

I will the info you requested next week.

**Comment by nirs** [comment]
So I tested again with increase log verbosity using:

```
--- a/test/addons/ocm-controller/kustomization.yaml
+++ b/test/addons/ocm-controller/kustomization.yaml
@@ -35,5 +35,8 @@ patches:
     name: ocm-controller
   patch: |-
     - op: add
       path: /spec/template/spec/containers/0/args/-
       value: "--agent-addon-image=quay.io/stolostron/multicloud-manager:latest"
+    - op: add
+      path: /spec/template/spec/containers/0/args/-
+      value: "--v=10"
```

manifestwork is not created for work-manger:

```
$ kubectl get manifestwork -n dr1 --context hub
NAME                                         AGE
addon-application-manager-deploy-0           4m24s
addon-config-policy-controller-deploy-0      4m24s
addon-governance-policy-framework-deploy-0   4m19s

$ kubectl get manifestwork -n dr2 --context hub
NAME                                         AGE
addon-application-manager-deploy-0           4m38s
addon-config-policy-controller-deploy-0      4m38s
addon-governance-policy-framework-deploy-0   4m34s
```

Please find the log here: 
[ocm-controller.log.gz](https://github.com/stolostron/multicloud-operators-foundation/files/11566916/ocm-controller.log.gz)

**Comment by zhiweiyin318** [comment]
@nirs we did not run this addon on non-OCP clusters, and I tested in 2 KinD clusters, did not reproduce your issue.  
the ocm-controller can work, but ocm-webhook and ocm-proxyserver cannot run.

ocm-controller creates work-manager addon CR for every managed cluster automatically, so we do not need to run  `clusteradm addon enable` command.  

there is no any error about `addon-deploy-controller`.  and I only found `error:namespaces "dr1" not found` error in the logs.  but the dr ns existed,  that's weird. 

how about the the managedCluster status?  is available right? 
please help check the conditions in the managedClusterAddon work-manager status.

**Comment by nirs** [comment]
@zhiweiyin318 thanks for looking at this~

> ocm-controller creates work-manager addon CR for every managed cluster automatically, so we do not need to run `clusteradm addon enable` command.

This did not work for us, so we added this commit:
https://github.com/RamenDR/ramen/commit/b4cc535b0c29bfaf5a9ff96698997ce5a942dac1

With this commit work-manager worked until last week. Maybe it works like that only on OCP?

> there is no any error about `addon-deploy-controller`. and I only found `error:namespaces "dr1" not found` error in the logs. but the dr ns existed, that's weird 

Indeed.

> how about the the managedCluster status? is available right? 

What do you mean by `managedCluster status`?

> please help check the conditions in the managedClusterAddon work-manager status, and whether the owner of addon cr is clustermanagementaddons work-manager.

I hope this info included in the yaml output.

Maybe we have a timing issue when installing ocm-controller? We install ocm-controller at the same time we join the managed clusters to hub. So when ocm-controller starts, it may or may not find the managed clusters, or they may be ready yet.

Do we have any dependency on the managed cluster in ocm-controller, and we need to install
it only after the managed cluster were added and all the addon were enabled? I guess not 
since the system is event based and it should detect when the managed clusters are ready
and do that right thing, but maybe my expectations are incorrect.

**Comment by nirs** [comment]
Adding requested info: 

managedcluster statuses:

```
$ kubectl get managedclusters/dr1 -A --context hub -o jsonpath='{.status}' | jq
{
  "allocatable": {
    "cpu": "2",
    "ephemeral-storage": "18215116Ki",
    "hugepages-2Mi": "0",
    "memory": "4012808Ki",
    "pods": "110"
  },
  "capacity": {
    "core_worker": "2",
    "cpu": "2",
    "ephemeral-storage": "18215116Ki",
    "hugepages-2Mi": "0",
    "memory": "4012808Ki",
    "pods": "110",
    "socket_worker": "0"
  },
  "conditions": [
    {
      "lastTransitionTime": "2023-05-28T16:18:12Z",
      "message": "Accepted by hub cluster admin",
      "reason": "HubClusterAdminAccepted",
      "status": "True",
      "type": "HubAcceptedManagedCluster"
    },
    {
      "lastTransitionTime": "2023-05-28T16:18:13Z",
      "message": "Managed cluster joined",
      "reason": "ManagedClusterJoined",
      "status": "True",
      "type": "ManagedClusterJoined"
    },
    {
      "lastTransitionTime": "2023-05-28T16:18:13Z",
      "message": "Managed cluster is available",
      "reason": "ManagedClusterAvailable",
      "status": "True",
      "type": "ManagedClusterConditionAvailable"
    }
  ],
  "version": {
    "kubernetes": "v1.26.3"
  }
}
```

```
$ kubectl get managedclusters/dr2 -A --context hub -o jsonpath='{.status}' | jq
{
  "allocatable": {
    "cpu": "2",
    "ephemeral-storage": "18215116Ki",
    "hugepages-2Mi": "0",
    "memory": "4012800Ki",
    "pods": "110"
  },
  "capacity": {
    "core_worker": "2",
    "cpu": "2",
    "ephemeral-storage": "18215116Ki",
    "hugepages-2Mi": "0",
    "memory": "4012800Ki",
    "pods": "110",
    "socket_worker": "0"
  },
  "conditions": [
    {
      "lastTransitionTime": "2023-05-28T16:18:14Z",
      "message": "Accepted by hub cluster admin",
      "reason": "HubClusterAdminAccepted",
      "status": "True",
      "type": "HubAcceptedManagedCluster"
    },
    {
      "lastTransitionTime": "2023-05-28T16:18:14Z",
      "message": "Managed cluster joined",
      "reason": "ManagedClusterJoined",
      "status": "True",
      "type": "ManagedClusterJoined"
    },
    {
      "lastTransitionTime": "2023-05-28T16:18:15Z",
      "message": "Managed cluster is available",
      "reason": "ManagedClusterAvailable",
      "status": "True",
      "type": "ManagedClusterConditionAvailable"
    }
  ],
  "version": {
    "kubernetes": "v1.26.3"
  }
}

```

work-manager addon:

```
$ kubectl get managedclusteraddon/work-manager -n dr1 --context hub -o yaml
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  creationTimestamp: "2023-05-28T16:18:22Z"
  generation: 1
  name: work-manager
  namespace: dr1
  resourceVersion: "1193"
  uid: 7345e9d8-842b-4daf-b555-c222c4ea7e86
spec:
  installNamespace: open-cluster-management-agent-addon
status:
  conditions:
  - lastTransitionTime: "2023-05-28T16:18:43Z"
    message: The status of work-manager add-on is unknown.
    reason: ManagedClusterAddOnLeaseNotFound
    status: Unknown
    type: Available
```

for reference, application-manager addon:

``
$ kubectl get managedclusteraddon/application-manager -n dr1 --context hub -o yaml
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  creationTimestamp: "2023-05-28T16:18:12Z"
  finalizers:
  - cluster.open-cluster-management.io/addon-pre-delete
  generation: 1
  name: application-manager
  namespace: dr1
  resourceVersion: "1352"
  uid: fc28a33b-989c-41d5-9e89-bd05dfd187a9
spec:
  installNamespace: open-cluster-management-agent-addon
status:
  conditions:
  - lastTransitionTime: "2023-05-28T16:18:14Z"
    message: Registration of the addon agent is configured
    reason: RegistrationConfigured
    status: "True"
    type: RegistrationApplied
  - lastTransitionTime: "2023-05-28T16:18:14Z"
    message: client certificate rotated starting from 2023-05-28 16:13:14 +0000 UTC
      to 2024-05-27 16:13:14 +0000 UTC
    reason: ClientCertificateUpdated
    status: "True"
    type: ClusterCertificateRotated
  - lastTransitionTime: "2023-05-28T16:18:49Z"
    message: manifests of addon are applied successfully
    reason: AddonManifestApplied
    status: "True"
    type: ManifestApplied
  - lastTransitionTime: "2023-05-28T16:19:13Z"
    message: application-manager add-on is available.
    reason: ManagedClusterAddOnLeaseUpdated
    status: "True"
    type: Available
  registrations:
  - signerName: kubernetes.io/kube-apiserver-client
    subject:
      groups:
      - system:open-cluster-management:cluster:dr1:addon:application-manager
      - system:open-cluster-management:addon:application-manager
      - system:authenticated
      user: system:open-cluster-management:cluster:dr1:addon:application-manager:agent:application-manager
```

**Comment by zhiweiyin318** [comment]
@nirs  the managedCluster is available. and there is no owner in the managedClusterAddon work-manager. I think the most possible is that you did not install clusterManagmentAddon work-manager https://github.com/stolostron/multicloud-operators-foundation/blob/main/deploy/foundation/hub/resources/clustermanagementaddon.yaml . 
In the latest add-framework, clusterManagmentAddon is required for each addon.

**Comment by nirs** [comment]
This issue is fixed in ramen by https://github.com/RamenDR/ramen/pull/900.

Closing since this is not an issue in this project.
